### ISSUE TITLE
3. Lesson Design feedback

### ISSUE THREAD

**Issue by PunamA** [bertozzivill/train-the-trainers#8]
- [x] Fix images
- [x] remove section discussing specifically carpentries learning (e.g. "In The Carpentries....")
- [x] consider adding additional information about how you might think of lesson design under long- and short- lesson plans as differently.
- [x] Exercise can be changed to have them make small group and see if they can come up with a lesson idea together for 10 minutes?

**Comment by bertozzivill** [comment]
many thanks for the comments! Incorporated, closing now.
